### ISSUE TITLE
Individual photo page

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#8]
Individual photo view. Contains 
- full photo
- user
- location
- timestap
- all other available meta
- links to OSM objects if associated
- action: download
- action: edit meta
- actions: add/edit/remove OSM objects
- action: delete photo

**Comment by vgeorge** [comment]
Remaining items for this page:

- [ ] Real image from the API
- [ ] User's display name instead of id
- [ ] Single OSM id for related object, instead of array
- [ ] Format date as in wireframe
- [ ] Allow editing the description
- [ ] Enable delete photo button
- [ ] Enable Download photo

Please add items and/or open specific issues if needed.

**Comment by vgeorge** [comment]
Implemented.
