### ISSUE TITLE
Individual trace page

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/observe-dashboard#9]
Individual trace page. Contains:
- mapped trace
- user
- timestamp (Start & End?)
- coordinates (Start & End?)
- action: edit in JOSM
- action: update trace meta
- action: delete trace

**Comment by vgeorge** [comment]
Looks good to me. I believe it is in line with OSM trace pages:

https://www.openstreetmap.org/user/vgeorge/traces/1227616

It might be better to use the term "Export to JOSM" instead of "Edit in JOSM". I believe the last gives the impression that a trace can be edited in Observe via JOSM.

**Comment by vgeorge** [comment]
Remaining items for this page:

- [ ] User's display name instead of id https://github.com/developmentseed/observe-api/issues/29
- [ ] Format date as in wireframe #28
- [ ] Allow description edit
- [ ] Enable "Delete photo" button
- [ ] Enable "Export to JOSM" button

Please add items and/or open specific issues if needed.

**Comment by vgeorge** [comment]
Implemented.
